const shoppingWords = [
  "cart",
  "checkout",
  "discount",
  "coupon",
  "sale",
  "bargain",
  "store",
  "mall",
  "voucher",
  "shop",
  "product",
  "item",
  "receipt",
  "price",
  "deal",
  "advertisement",
  "promotion",
  "offer",
  "return",
  "refund",
  "purchase",
  "receipt",
  "fashion",
  "clothing",
  "electronics",
  "groceries",
  "payment",
  "credit",
  "debit",
  "giftcard",
  "wishlist",
  "brand",
  "review",
  "rating",
  "shipping",
  "delivery",
  "checkout",
  "cashback",
  "price tag",
  "purchase",
  "transaction",
  "warehouse",
  "customer",
  "storefront",
  "store manager",
  "supplier",
  "shopping spree",
  "sales tax",
  "merchant",
  "loyalty program",
  "gift",
  "shopping cart",
  "shopping bag",
  "inventory",
];

function generateRandomPassword() {
  const randomIndex = Math.floor(Math.random() * shoppingWords.length);
  return shoppingWords[randomIndex];
}

module.exports = { generateRandomPassword };
